apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro2
  namespace: tp2
spec:
  selector:
    matchLabels:
      app: micro2
  template:
    metadata:
      labels:
        app: micro2
    spec:
      containers:
      - name: micro2
        image: allaismail/microservice2_profession
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: password
        - name: POSTGRES_IP
          value: postgres2-service
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_DB
          value: micro2_db
        ports:
        - containerPort: 8000

