apiVersion: v1
kind: Service
metadata:
  name: postgres2-service
  namespace: tp2
  labels:
    app: postgres2
spec:
  ports:
  - port: 5432
    name: postgres2
  type: ClusterIP
  selector:
    app: postgres2