apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres2-statefulset
  namespace: tp2
  labels:
    app: postgres2
spec:
  serviceName: "postgres2"
  replicas: 1
  selector:
    matchLabels:
      app: postgres2
  template:
    metadata:
      labels:
        app: postgres2
    spec:
      containers:
      - name: postgres2
        image: postgres:12
        envFrom:
        - configMapRef:
            name: postgres-configuration-m2
        ports:
        - containerPort: 5432
          name: postgres2db